/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAppointmentsRouteImport } from './routes/_authenticated/appointments'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDepartmentsRouteImport } from './routes/_authenticated/departments'
import { Route as AuthenticatedEmployeesRouteImport } from './routes/_authenticated/employees'
import { Route as AuthenticatedPatientsRouteImport } from './routes/_authenticated/patients'
import { Route as AuthenticatedPositionsRouteImport } from './routes/_authenticated/positions'
import { Route as AuthenticatedRoomsRouteImport } from './routes/_authenticated/rooms'
import { Route as AuthenticatedShiftsRouteImport } from './routes/_authenticated/shifts'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin.dashboard'
import { Route as AuthenticatedAdminIssuesRouteImport } from './routes/_authenticated/admin.issues'
import { Route as AuthenticatedAppointmentsBookingRouteImport } from './routes/_authenticated/appointments.booking'
import { Route as AuthenticatedAppointmentsCalendarRouteImport } from './routes/_authenticated/appointments.calendar'
import { Route as AuthenticatedAttendanceAdjustmentsRouteImport } from './routes/_authenticated/attendance.adjustments'
import { Route as AuthenticatedAttendanceCheckinRouteImport } from './routes/_authenticated/attendance.checkin'
import { Route as AuthenticatedAttendanceDailyRouteImport } from './routes/_authenticated/attendance.daily'
import { Route as AuthenticatedAttendanceLogsRouteImport } from './routes/_authenticated/attendance.logs'
import { Route as AuthenticatedAttendanceManualRouteImport } from './routes/_authenticated/attendance.manual'
import { Route as AuthenticatedAttendanceMonthlyRouteImport } from './routes/_authenticated/attendance.monthly'
import { Route as AuthenticatedAttendanceOvertimeRouteImport } from './routes/_authenticated/attendance.overtime'
import { Route as AuthenticatedBiometricDevicesRouteImport } from './routes/_authenticated/biometric.devices'
import { Route as AuthenticatedDoctorDashboardRouteImport } from './routes/_authenticated/doctor.dashboard'
import { Route as AuthenticatedDoctorProfileRouteImport } from './routes/_authenticated/doctor.profile'
import { Route as AuthenticatedDoctorScheduleRouteImport } from './routes/_authenticated/doctor.schedule'
import { Route as AuthenticatedHrAssignmentsRouteImport } from './routes/_authenticated/hr.assignments'
import { Route as AuthenticatedHrPayrollRouteImport } from './routes/_authenticated/hr.payroll'
import { Route as AuthenticatedHrSalaryRouteImport } from './routes/_authenticated/hr.salary'
import { Route as AuthenticatedIssuesMyReportsRouteImport } from './routes/_authenticated/issues.my-reports'
import { Route as AuthenticatedIssuesReportRouteImport } from './routes/_authenticated/issues.report'
import { Route as AuthenticatedPatientProfileRouteImport } from './routes/_authenticated/patient.profile'
import { Route as AuthenticatedReportsAppointmentsRouteImport } from './routes/_authenticated/reports.appointments'
import { Route as AuthenticatedReportsAttendanceRouteImport } from './routes/_authenticated/reports.attendance'
import { Route as AuthenticatedReportsExportRouteImport } from './routes/_authenticated/reports.export'
import { Route as AuthenticatedStaffProfilesRouteImport } from './routes/_authenticated/staff.profiles'
import { Route as AuthenticatedSystemAgentRouteImport } from './routes/_authenticated/system.agent'
import { Route as AuthenticatedSystemAuditLogsRouteImport } from './routes/_authenticated/system.audit-logs'
import { Route as AuthenticatedSystemClinicProfileRouteImport } from './routes/_authenticated/system.clinic-profile'
import { Route as AuthenticatedSystemDevicesRouteImport } from './routes/_authenticated/system.devices'
import { Route as AuthenticatedSystemSettingsRouteImport } from './routes/_authenticated/system.settings'
import { Route as AuthenticatedSystemSyncRouteImport } from './routes/_authenticated/system.sync'
import { Route as AuthenticatedSystemUsersRouteImport } from './routes/_authenticated/system.users'
import { Route as ApiPublicDeviceEventsRouteImport } from './routes/api/public/device/events'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppointmentsRoute =
  AuthenticatedAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepartmentsRoute =
  AuthenticatedDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployeesRoute = AuthenticatedEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatientsRoute = AuthenticatedPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPositionsRoute = AuthenticatedPositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoomsRoute = AuthenticatedRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShiftsRoute = AuthenticatedShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIssuesRoute =
  AuthenticatedAdminIssuesRouteImport.update({
    id: '/admin/issues',
    path: '/admin/issues',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppointmentsBookingRoute =
  AuthenticatedAppointmentsBookingRouteImport.update({
    id: '/booking',
    path: '/booking',
    getParentRoute: () => AuthenticatedAppointmentsRoute,
  } as any)
const AuthenticatedAppointmentsCalendarRoute =
  AuthenticatedAppointmentsCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedAppointmentsRoute,
  } as any)
const AuthenticatedAttendanceAdjustmentsRoute =
  AuthenticatedAttendanceAdjustmentsRouteImport.update({
    id: '/attendance/adjustments',
    path: '/attendance/adjustments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceCheckinRoute =
  AuthenticatedAttendanceCheckinRouteImport.update({
    id: '/attendance/checkin',
    path: '/attendance/checkin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceDailyRoute =
  AuthenticatedAttendanceDailyRouteImport.update({
    id: '/attendance/daily',
    path: '/attendance/daily',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceLogsRoute =
  AuthenticatedAttendanceLogsRouteImport.update({
    id: '/attendance/logs',
    path: '/attendance/logs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceManualRoute =
  AuthenticatedAttendanceManualRouteImport.update({
    id: '/attendance/manual',
    path: '/attendance/manual',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceMonthlyRoute =
  AuthenticatedAttendanceMonthlyRouteImport.update({
    id: '/attendance/monthly',
    path: '/attendance/monthly',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceOvertimeRoute =
  AuthenticatedAttendanceOvertimeRouteImport.update({
    id: '/attendance/overtime',
    path: '/attendance/overtime',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBiometricDevicesRoute =
  AuthenticatedBiometricDevicesRouteImport.update({
    id: '/biometric/devices',
    path: '/biometric/devices',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDoctorDashboardRoute =
  AuthenticatedDoctorDashboardRouteImport.update({
    id: '/doctor/dashboard',
    path: '/doctor/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDoctorProfileRoute =
  AuthenticatedDoctorProfileRouteImport.update({
    id: '/doctor/profile',
    path: '/doctor/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDoctorScheduleRoute =
  AuthenticatedDoctorScheduleRouteImport.update({
    id: '/doctor/schedule',
    path: '/doctor/schedule',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrAssignmentsRoute =
  AuthenticatedHrAssignmentsRouteImport.update({
    id: '/hr/assignments',
    path: '/hr/assignments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrPayrollRoute = AuthenticatedHrPayrollRouteImport.update({
  id: '/hr/payroll',
  path: '/hr/payroll',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHrSalaryRoute = AuthenticatedHrSalaryRouteImport.update({
  id: '/hr/salary',
  path: '/hr/salary',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIssuesMyReportsRoute =
  AuthenticatedIssuesMyReportsRouteImport.update({
    id: '/issues/my-reports',
    path: '/issues/my-reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIssuesReportRoute =
  AuthenticatedIssuesReportRouteImport.update({
    id: '/issues/report',
    path: '/issues/report',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientProfileRoute =
  AuthenticatedPatientProfileRouteImport.update({
    id: '/patient/profile',
    path: '/patient/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsAppointmentsRoute =
  AuthenticatedReportsAppointmentsRouteImport.update({
    id: '/reports/appointments',
    path: '/reports/appointments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsAttendanceRoute =
  AuthenticatedReportsAttendanceRouteImport.update({
    id: '/reports/attendance',
    path: '/reports/attendance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsExportRoute =
  AuthenticatedReportsExportRouteImport.update({
    id: '/reports/export',
    path: '/reports/export',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffProfilesRoute =
  AuthenticatedStaffProfilesRouteImport.update({
    id: '/staff/profiles',
    path: '/staff/profiles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemAgentRoute =
  AuthenticatedSystemAgentRouteImport.update({
    id: '/system/agent',
    path: '/system/agent',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemAuditLogsRoute =
  AuthenticatedSystemAuditLogsRouteImport.update({
    id: '/system/audit-logs',
    path: '/system/audit-logs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemClinicProfileRoute =
  AuthenticatedSystemClinicProfileRouteImport.update({
    id: '/system/clinic-profile',
    path: '/system/clinic-profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemDevicesRoute =
  AuthenticatedSystemDevicesRouteImport.update({
    id: '/system/devices',
    path: '/system/devices',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemSettingsRoute =
  AuthenticatedSystemSettingsRouteImport.update({
    id: '/system/settings',
    path: '/system/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemSyncRoute = AuthenticatedSystemSyncRouteImport.update({
  id: '/system/sync',
  path: '/system/sync',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSystemUsersRoute =
  AuthenticatedSystemUsersRouteImport.update({
    id: '/system/users',
    path: '/system/users',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicDeviceEventsRoute = ApiPublicDeviceEventsRouteImport.update({
  id: '/api/public/device/events',
  path: '/api/public/device/events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/appointments': typeof AuthenticatedAppointmentsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/patients': typeof AuthenticatedPatientsRoute
  '/positions': typeof AuthenticatedPositionsRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/shifts': typeof AuthenticatedShiftsRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/issues': typeof AuthenticatedAdminIssuesRoute
  '/appointments/booking': typeof AuthenticatedAppointmentsBookingRoute
  '/appointments/calendar': typeof AuthenticatedAppointmentsCalendarRoute
  '/attendance/adjustments': typeof AuthenticatedAttendanceAdjustmentsRoute
  '/attendance/checkin': typeof AuthenticatedAttendanceCheckinRoute
  '/attendance/daily': typeof AuthenticatedAttendanceDailyRoute
  '/attendance/logs': typeof AuthenticatedAttendanceLogsRoute
  '/attendance/manual': typeof AuthenticatedAttendanceManualRoute
  '/attendance/monthly': typeof AuthenticatedAttendanceMonthlyRoute
  '/attendance/overtime': typeof AuthenticatedAttendanceOvertimeRoute
  '/biometric/devices': typeof AuthenticatedBiometricDevicesRoute
  '/doctor/dashboard': typeof AuthenticatedDoctorDashboardRoute
  '/doctor/profile': typeof AuthenticatedDoctorProfileRoute
  '/doctor/schedule': typeof AuthenticatedDoctorScheduleRoute
  '/hr/assignments': typeof AuthenticatedHrAssignmentsRoute
  '/hr/payroll': typeof AuthenticatedHrPayrollRoute
  '/hr/salary': typeof AuthenticatedHrSalaryRoute
  '/issues/my-reports': typeof AuthenticatedIssuesMyReportsRoute
  '/issues/report': typeof AuthenticatedIssuesReportRoute
  '/patient/profile': typeof AuthenticatedPatientProfileRoute
  '/reports/appointments': typeof AuthenticatedReportsAppointmentsRoute
  '/reports/attendance': typeof AuthenticatedReportsAttendanceRoute
  '/reports/export': typeof AuthenticatedReportsExportRoute
  '/staff/profiles': typeof AuthenticatedStaffProfilesRoute
  '/system/agent': typeof AuthenticatedSystemAgentRoute
  '/system/audit-logs': typeof AuthenticatedSystemAuditLogsRoute
  '/system/clinic-profile': typeof AuthenticatedSystemClinicProfileRoute
  '/system/devices': typeof AuthenticatedSystemDevicesRoute
  '/system/settings': typeof AuthenticatedSystemSettingsRoute
  '/system/sync': typeof AuthenticatedSystemSyncRoute
  '/system/users': typeof AuthenticatedSystemUsersRoute
  '/api/public/device/events': typeof ApiPublicDeviceEventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/appointments': typeof AuthenticatedAppointmentsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/patients': typeof AuthenticatedPatientsRoute
  '/positions': typeof AuthenticatedPositionsRoute
  '/rooms': typeof AuthenticatedRoomsRoute
  '/shifts': typeof AuthenticatedShiftsRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/issues': typeof AuthenticatedAdminIssuesRoute
  '/appointments/booking': typeof AuthenticatedAppointmentsBookingRoute
  '/appointments/calendar': typeof AuthenticatedAppointmentsCalendarRoute
  '/attendance/adjustments': typeof AuthenticatedAttendanceAdjustmentsRoute
  '/attendance/checkin': typeof AuthenticatedAttendanceCheckinRoute
  '/attendance/daily': typeof AuthenticatedAttendanceDailyRoute
  '/attendance/logs': typeof AuthenticatedAttendanceLogsRoute
  '/attendance/manual': typeof AuthenticatedAttendanceManualRoute
  '/attendance/monthly': typeof AuthenticatedAttendanceMonthlyRoute
  '/attendance/overtime': typeof AuthenticatedAttendanceOvertimeRoute
  '/biometric/devices': typeof AuthenticatedBiometricDevicesRoute
  '/doctor/dashboard': typeof AuthenticatedDoctorDashboardRoute
  '/doctor/profile': typeof AuthenticatedDoctorProfileRoute
  '/doctor/schedule': typeof AuthenticatedDoctorScheduleRoute
  '/hr/assignments': typeof AuthenticatedHrAssignmentsRoute
  '/hr/payroll': typeof AuthenticatedHrPayrollRoute
  '/hr/salary': typeof AuthenticatedHrSalaryRoute
  '/issues/my-reports': typeof AuthenticatedIssuesMyReportsRoute
  '/issues/report': typeof AuthenticatedIssuesReportRoute
  '/patient/profile': typeof AuthenticatedPatientProfileRoute
  '/reports/appointments': typeof AuthenticatedReportsAppointmentsRoute
  '/reports/attendance': typeof AuthenticatedReportsAttendanceRoute
  '/reports/export': typeof AuthenticatedReportsExportRoute
  '/staff/profiles': typeof AuthenticatedStaffProfilesRoute
  '/system/agent': typeof AuthenticatedSystemAgentRoute
  '/system/audit-logs': typeof AuthenticatedSystemAuditLogsRoute
  '/system/clinic-profile': typeof AuthenticatedSystemClinicProfileRoute
  '/system/devices': typeof AuthenticatedSystemDevicesRoute
  '/system/settings': typeof AuthenticatedSystemSettingsRoute
  '/system/sync': typeof AuthenticatedSystemSyncRoute
  '/system/users': typeof AuthenticatedSystemUsersRoute
  '/api/public/device/events': typeof ApiPublicDeviceEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/departments': typeof AuthenticatedDepartmentsRoute
  '/_authenticated/employees': typeof AuthenticatedEmployeesRoute
  '/_authenticated/patients': typeof AuthenticatedPatientsRoute
  '/_authenticated/positions': typeof AuthenticatedPositionsRoute
  '/_authenticated/rooms': typeof AuthenticatedRoomsRoute
  '/_authenticated/shifts': typeof AuthenticatedShiftsRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/issues': typeof AuthenticatedAdminIssuesRoute
  '/_authenticated/appointments/booking': typeof AuthenticatedAppointmentsBookingRoute
  '/_authenticated/appointments/calendar': typeof AuthenticatedAppointmentsCalendarRoute
  '/_authenticated/attendance/adjustments': typeof AuthenticatedAttendanceAdjustmentsRoute
  '/_authenticated/attendance/checkin': typeof AuthenticatedAttendanceCheckinRoute
  '/_authenticated/attendance/daily': typeof AuthenticatedAttendanceDailyRoute
  '/_authenticated/attendance/logs': typeof AuthenticatedAttendanceLogsRoute
  '/_authenticated/attendance/manual': typeof AuthenticatedAttendanceManualRoute
  '/_authenticated/attendance/monthly': typeof AuthenticatedAttendanceMonthlyRoute
  '/_authenticated/attendance/overtime': typeof AuthenticatedAttendanceOvertimeRoute
  '/_authenticated/biometric/devices': typeof AuthenticatedBiometricDevicesRoute
  '/_authenticated/doctor/dashboard': typeof AuthenticatedDoctorDashboardRoute
  '/_authenticated/doctor/profile': typeof AuthenticatedDoctorProfileRoute
  '/_authenticated/doctor/schedule': typeof AuthenticatedDoctorScheduleRoute
  '/_authenticated/hr/assignments': typeof AuthenticatedHrAssignmentsRoute
  '/_authenticated/hr/payroll': typeof AuthenticatedHrPayrollRoute
  '/_authenticated/hr/salary': typeof AuthenticatedHrSalaryRoute
  '/_authenticated/issues/my-reports': typeof AuthenticatedIssuesMyReportsRoute
  '/_authenticated/issues/report': typeof AuthenticatedIssuesReportRoute
  '/_authenticated/patient/profile': typeof AuthenticatedPatientProfileRoute
  '/_authenticated/reports/appointments': typeof AuthenticatedReportsAppointmentsRoute
  '/_authenticated/reports/attendance': typeof AuthenticatedReportsAttendanceRoute
  '/_authenticated/reports/export': typeof AuthenticatedReportsExportRoute
  '/_authenticated/staff/profiles': typeof AuthenticatedStaffProfilesRoute
  '/_authenticated/system/agent': typeof AuthenticatedSystemAgentRoute
  '/_authenticated/system/audit-logs': typeof AuthenticatedSystemAuditLogsRoute
  '/_authenticated/system/clinic-profile': typeof AuthenticatedSystemClinicProfileRoute
  '/_authenticated/system/devices': typeof AuthenticatedSystemDevicesRoute
  '/_authenticated/system/settings': typeof AuthenticatedSystemSettingsRoute
  '/_authenticated/system/sync': typeof AuthenticatedSystemSyncRoute
  '/_authenticated/system/users': typeof AuthenticatedSystemUsersRoute
  '/api/public/device/events': typeof ApiPublicDeviceEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/appointments'
    | '/dashboard'
    | '/departments'
    | '/employees'
    | '/patients'
    | '/positions'
    | '/rooms'
    | '/shifts'
    | '/admin/dashboard'
    | '/admin/issues'
    | '/appointments/booking'
    | '/appointments/calendar'
    | '/attendance/adjustments'
    | '/attendance/checkin'
    | '/attendance/daily'
    | '/attendance/logs'
    | '/attendance/manual'
    | '/attendance/monthly'
    | '/attendance/overtime'
    | '/biometric/devices'
    | '/doctor/dashboard'
    | '/doctor/profile'
    | '/doctor/schedule'
    | '/hr/assignments'
    | '/hr/payroll'
    | '/hr/salary'
    | '/issues/my-reports'
    | '/issues/report'
    | '/patient/profile'
    | '/reports/appointments'
    | '/reports/attendance'
    | '/reports/export'
    | '/staff/profiles'
    | '/system/agent'
    | '/system/audit-logs'
    | '/system/clinic-profile'
    | '/system/devices'
    | '/system/settings'
    | '/system/sync'
    | '/system/users'
    | '/api/public/device/events'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/appointments'
    | '/dashboard'
    | '/departments'
    | '/employees'
    | '/patients'
    | '/positions'
    | '/rooms'
    | '/shifts'
    | '/admin/dashboard'
    | '/admin/issues'
    | '/appointments/booking'
    | '/appointments/calendar'
    | '/attendance/adjustments'
    | '/attendance/checkin'
    | '/attendance/daily'
    | '/attendance/logs'
    | '/attendance/manual'
    | '/attendance/monthly'
    | '/attendance/overtime'
    | '/biometric/devices'
    | '/doctor/dashboard'
    | '/doctor/profile'
    | '/doctor/schedule'
    | '/hr/assignments'
    | '/hr/payroll'
    | '/hr/salary'
    | '/issues/my-reports'
    | '/issues/report'
    | '/patient/profile'
    | '/reports/appointments'
    | '/reports/attendance'
    | '/reports/export'
    | '/staff/profiles'
    | '/system/agent'
    | '/system/audit-logs'
    | '/system/clinic-profile'
    | '/system/devices'
    | '/system/settings'
    | '/system/sync'
    | '/system/users'
    | '/api/public/device/events'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/appointments'
    | '/_authenticated/dashboard'
    | '/_authenticated/departments'
    | '/_authenticated/employees'
    | '/_authenticated/patients'
    | '/_authenticated/positions'
    | '/_authenticated/rooms'
    | '/_authenticated/shifts'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/issues'
    | '/_authenticated/appointments/booking'
    | '/_authenticated/appointments/calendar'
    | '/_authenticated/attendance/adjustments'
    | '/_authenticated/attendance/checkin'
    | '/_authenticated/attendance/daily'
    | '/_authenticated/attendance/logs'
    | '/_authenticated/attendance/manual'
    | '/_authenticated/attendance/monthly'
    | '/_authenticated/attendance/overtime'
    | '/_authenticated/biometric/devices'
    | '/_authenticated/doctor/dashboard'
    | '/_authenticated/doctor/profile'
    | '/_authenticated/doctor/schedule'
    | '/_authenticated/hr/assignments'
    | '/_authenticated/hr/payroll'
    | '/_authenticated/hr/salary'
    | '/_authenticated/issues/my-reports'
    | '/_authenticated/issues/report'
    | '/_authenticated/patient/profile'
    | '/_authenticated/reports/appointments'
    | '/_authenticated/reports/attendance'
    | '/_authenticated/reports/export'
    | '/_authenticated/staff/profiles'
    | '/_authenticated/system/agent'
    | '/_authenticated/system/audit-logs'
    | '/_authenticated/system/clinic-profile'
    | '/_authenticated/system/devices'
    | '/_authenticated/system/settings'
    | '/_authenticated/system/sync'
    | '/_authenticated/system/users'
    | '/api/public/device/events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicDeviceEventsRoute: typeof ApiPublicDeviceEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/departments': {
      id: '/_authenticated/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AuthenticatedDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employees': {
      id: '/_authenticated/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients': {
      id: '/_authenticated/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AuthenticatedPatientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/positions': {
      id: '/_authenticated/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof AuthenticatedPositionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rooms': {
      id: '/_authenticated/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AuthenticatedRoomsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shifts': {
      id: '/_authenticated/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof AuthenticatedShiftsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/issues': {
      id: '/_authenticated/admin/issues'
      path: '/admin/issues'
      fullPath: '/admin/issues'
      preLoaderRoute: typeof AuthenticatedAdminIssuesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appointments/booking': {
      id: '/_authenticated/appointments/booking'
      path: '/booking'
      fullPath: '/appointments/booking'
      preLoaderRoute: typeof AuthenticatedAppointmentsBookingRouteImport
      parentRoute: typeof AuthenticatedAppointmentsRoute
    }
    '/_authenticated/appointments/calendar': {
      id: '/_authenticated/appointments/calendar'
      path: '/calendar'
      fullPath: '/appointments/calendar'
      preLoaderRoute: typeof AuthenticatedAppointmentsCalendarRouteImport
      parentRoute: typeof AuthenticatedAppointmentsRoute
    }
    '/_authenticated/attendance/adjustments': {
      id: '/_authenticated/attendance/adjustments'
      path: '/attendance/adjustments'
      fullPath: '/attendance/adjustments'
      preLoaderRoute: typeof AuthenticatedAttendanceAdjustmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/checkin': {
      id: '/_authenticated/attendance/checkin'
      path: '/attendance/checkin'
      fullPath: '/attendance/checkin'
      preLoaderRoute: typeof AuthenticatedAttendanceCheckinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/daily': {
      id: '/_authenticated/attendance/daily'
      path: '/attendance/daily'
      fullPath: '/attendance/daily'
      preLoaderRoute: typeof AuthenticatedAttendanceDailyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/logs': {
      id: '/_authenticated/attendance/logs'
      path: '/attendance/logs'
      fullPath: '/attendance/logs'
      preLoaderRoute: typeof AuthenticatedAttendanceLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/manual': {
      id: '/_authenticated/attendance/manual'
      path: '/attendance/manual'
      fullPath: '/attendance/manual'
      preLoaderRoute: typeof AuthenticatedAttendanceManualRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/monthly': {
      id: '/_authenticated/attendance/monthly'
      path: '/attendance/monthly'
      fullPath: '/attendance/monthly'
      preLoaderRoute: typeof AuthenticatedAttendanceMonthlyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/overtime': {
      id: '/_authenticated/attendance/overtime'
      path: '/attendance/overtime'
      fullPath: '/attendance/overtime'
      preLoaderRoute: typeof AuthenticatedAttendanceOvertimeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/biometric/devices': {
      id: '/_authenticated/biometric/devices'
      path: '/biometric/devices'
      fullPath: '/biometric/devices'
      preLoaderRoute: typeof AuthenticatedBiometricDevicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctor/dashboard': {
      id: '/_authenticated/doctor/dashboard'
      path: '/doctor/dashboard'
      fullPath: '/doctor/dashboard'
      preLoaderRoute: typeof AuthenticatedDoctorDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctor/profile': {
      id: '/_authenticated/doctor/profile'
      path: '/doctor/profile'
      fullPath: '/doctor/profile'
      preLoaderRoute: typeof AuthenticatedDoctorProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctor/schedule': {
      id: '/_authenticated/doctor/schedule'
      path: '/doctor/schedule'
      fullPath: '/doctor/schedule'
      preLoaderRoute: typeof AuthenticatedDoctorScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/assignments': {
      id: '/_authenticated/hr/assignments'
      path: '/hr/assignments'
      fullPath: '/hr/assignments'
      preLoaderRoute: typeof AuthenticatedHrAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/payroll': {
      id: '/_authenticated/hr/payroll'
      path: '/hr/payroll'
      fullPath: '/hr/payroll'
      preLoaderRoute: typeof AuthenticatedHrPayrollRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/salary': {
      id: '/_authenticated/hr/salary'
      path: '/hr/salary'
      fullPath: '/hr/salary'
      preLoaderRoute: typeof AuthenticatedHrSalaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/issues/my-reports': {
      id: '/_authenticated/issues/my-reports'
      path: '/issues/my-reports'
      fullPath: '/issues/my-reports'
      preLoaderRoute: typeof AuthenticatedIssuesMyReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/issues/report': {
      id: '/_authenticated/issues/report'
      path: '/issues/report'
      fullPath: '/issues/report'
      preLoaderRoute: typeof AuthenticatedIssuesReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patient/profile': {
      id: '/_authenticated/patient/profile'
      path: '/patient/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof AuthenticatedPatientProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/appointments': {
      id: '/_authenticated/reports/appointments'
      path: '/reports/appointments'
      fullPath: '/reports/appointments'
      preLoaderRoute: typeof AuthenticatedReportsAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/attendance': {
      id: '/_authenticated/reports/attendance'
      path: '/reports/attendance'
      fullPath: '/reports/attendance'
      preLoaderRoute: typeof AuthenticatedReportsAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/export': {
      id: '/_authenticated/reports/export'
      path: '/reports/export'
      fullPath: '/reports/export'
      preLoaderRoute: typeof AuthenticatedReportsExportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/profiles': {
      id: '/_authenticated/staff/profiles'
      path: '/staff/profiles'
      fullPath: '/staff/profiles'
      preLoaderRoute: typeof AuthenticatedStaffProfilesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/agent': {
      id: '/_authenticated/system/agent'
      path: '/system/agent'
      fullPath: '/system/agent'
      preLoaderRoute: typeof AuthenticatedSystemAgentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/audit-logs': {
      id: '/_authenticated/system/audit-logs'
      path: '/system/audit-logs'
      fullPath: '/system/audit-logs'
      preLoaderRoute: typeof AuthenticatedSystemAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/clinic-profile': {
      id: '/_authenticated/system/clinic-profile'
      path: '/system/clinic-profile'
      fullPath: '/system/clinic-profile'
      preLoaderRoute: typeof AuthenticatedSystemClinicProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/devices': {
      id: '/_authenticated/system/devices'
      path: '/system/devices'
      fullPath: '/system/devices'
      preLoaderRoute: typeof AuthenticatedSystemDevicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/settings': {
      id: '/_authenticated/system/settings'
      path: '/system/settings'
      fullPath: '/system/settings'
      preLoaderRoute: typeof AuthenticatedSystemSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/sync': {
      id: '/_authenticated/system/sync'
      path: '/system/sync'
      fullPath: '/system/sync'
      preLoaderRoute: typeof AuthenticatedSystemSyncRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/users': {
      id: '/_authenticated/system/users'
      path: '/system/users'
      fullPath: '/system/users'
      preLoaderRoute: typeof AuthenticatedSystemUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/device/events': {
      id: '/api/public/device/events'
      path: '/api/public/device/events'
      fullPath: '/api/public/device/events'
      preLoaderRoute: typeof ApiPublicDeviceEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAppointmentsRouteChildren {
  AuthenticatedAppointmentsBookingRoute: typeof AuthenticatedAppointmentsBookingRoute
  AuthenticatedAppointmentsCalendarRoute: typeof AuthenticatedAppointmentsCalendarRoute
}

const AuthenticatedAppointmentsRouteChildren: AuthenticatedAppointmentsRouteChildren =
  {
    AuthenticatedAppointmentsBookingRoute:
      AuthenticatedAppointmentsBookingRoute,
    AuthenticatedAppointmentsCalendarRoute:
      AuthenticatedAppointmentsCalendarRoute,
  }

const AuthenticatedAppointmentsRouteWithChildren =
  AuthenticatedAppointmentsRoute._addFileChildren(
    AuthenticatedAppointmentsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppointmentsRoute: typeof AuthenticatedAppointmentsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepartmentsRoute: typeof AuthenticatedDepartmentsRoute
  AuthenticatedEmployeesRoute: typeof AuthenticatedEmployeesRoute
  AuthenticatedPatientsRoute: typeof AuthenticatedPatientsRoute
  AuthenticatedPositionsRoute: typeof AuthenticatedPositionsRoute
  AuthenticatedRoomsRoute: typeof AuthenticatedRoomsRoute
  AuthenticatedShiftsRoute: typeof AuthenticatedShiftsRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminIssuesRoute: typeof AuthenticatedAdminIssuesRoute
  AuthenticatedAttendanceAdjustmentsRoute: typeof AuthenticatedAttendanceAdjustmentsRoute
  AuthenticatedAttendanceCheckinRoute: typeof AuthenticatedAttendanceCheckinRoute
  AuthenticatedAttendanceDailyRoute: typeof AuthenticatedAttendanceDailyRoute
  AuthenticatedAttendanceLogsRoute: typeof AuthenticatedAttendanceLogsRoute
  AuthenticatedAttendanceManualRoute: typeof AuthenticatedAttendanceManualRoute
  AuthenticatedAttendanceMonthlyRoute: typeof AuthenticatedAttendanceMonthlyRoute
  AuthenticatedAttendanceOvertimeRoute: typeof AuthenticatedAttendanceOvertimeRoute
  AuthenticatedBiometricDevicesRoute: typeof AuthenticatedBiometricDevicesRoute
  AuthenticatedDoctorDashboardRoute: typeof AuthenticatedDoctorDashboardRoute
  AuthenticatedDoctorProfileRoute: typeof AuthenticatedDoctorProfileRoute
  AuthenticatedDoctorScheduleRoute: typeof AuthenticatedDoctorScheduleRoute
  AuthenticatedHrAssignmentsRoute: typeof AuthenticatedHrAssignmentsRoute
  AuthenticatedHrPayrollRoute: typeof AuthenticatedHrPayrollRoute
  AuthenticatedHrSalaryRoute: typeof AuthenticatedHrSalaryRoute
  AuthenticatedIssuesMyReportsRoute: typeof AuthenticatedIssuesMyReportsRoute
  AuthenticatedIssuesReportRoute: typeof AuthenticatedIssuesReportRoute
  AuthenticatedPatientProfileRoute: typeof AuthenticatedPatientProfileRoute
  AuthenticatedReportsAppointmentsRoute: typeof AuthenticatedReportsAppointmentsRoute
  AuthenticatedReportsAttendanceRoute: typeof AuthenticatedReportsAttendanceRoute
  AuthenticatedReportsExportRoute: typeof AuthenticatedReportsExportRoute
  AuthenticatedStaffProfilesRoute: typeof AuthenticatedStaffProfilesRoute
  AuthenticatedSystemAgentRoute: typeof AuthenticatedSystemAgentRoute
  AuthenticatedSystemAuditLogsRoute: typeof AuthenticatedSystemAuditLogsRoute
  AuthenticatedSystemClinicProfileRoute: typeof AuthenticatedSystemClinicProfileRoute
  AuthenticatedSystemDevicesRoute: typeof AuthenticatedSystemDevicesRoute
  AuthenticatedSystemSettingsRoute: typeof AuthenticatedSystemSettingsRoute
  AuthenticatedSystemSyncRoute: typeof AuthenticatedSystemSyncRoute
  AuthenticatedSystemUsersRoute: typeof AuthenticatedSystemUsersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppointmentsRoute: AuthenticatedAppointmentsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepartmentsRoute: AuthenticatedDepartmentsRoute,
  AuthenticatedEmployeesRoute: AuthenticatedEmployeesRoute,
  AuthenticatedPatientsRoute: AuthenticatedPatientsRoute,
  AuthenticatedPositionsRoute: AuthenticatedPositionsRoute,
  AuthenticatedRoomsRoute: AuthenticatedRoomsRoute,
  AuthenticatedShiftsRoute: AuthenticatedShiftsRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminIssuesRoute: AuthenticatedAdminIssuesRoute,
  AuthenticatedAttendanceAdjustmentsRoute:
    AuthenticatedAttendanceAdjustmentsRoute,
  AuthenticatedAttendanceCheckinRoute: AuthenticatedAttendanceCheckinRoute,
  AuthenticatedAttendanceDailyRoute: AuthenticatedAttendanceDailyRoute,
  AuthenticatedAttendanceLogsRoute: AuthenticatedAttendanceLogsRoute,
  AuthenticatedAttendanceManualRoute: AuthenticatedAttendanceManualRoute,
  AuthenticatedAttendanceMonthlyRoute: AuthenticatedAttendanceMonthlyRoute,
  AuthenticatedAttendanceOvertimeRoute: AuthenticatedAttendanceOvertimeRoute,
  AuthenticatedBiometricDevicesRoute: AuthenticatedBiometricDevicesRoute,
  AuthenticatedDoctorDashboardRoute: AuthenticatedDoctorDashboardRoute,
  AuthenticatedDoctorProfileRoute: AuthenticatedDoctorProfileRoute,
  AuthenticatedDoctorScheduleRoute: AuthenticatedDoctorScheduleRoute,
  AuthenticatedHrAssignmentsRoute: AuthenticatedHrAssignmentsRoute,
  AuthenticatedHrPayrollRoute: AuthenticatedHrPayrollRoute,
  AuthenticatedHrSalaryRoute: AuthenticatedHrSalaryRoute,
  AuthenticatedIssuesMyReportsRoute: AuthenticatedIssuesMyReportsRoute,
  AuthenticatedIssuesReportRoute: AuthenticatedIssuesReportRoute,
  AuthenticatedPatientProfileRoute: AuthenticatedPatientProfileRoute,
  AuthenticatedReportsAppointmentsRoute: AuthenticatedReportsAppointmentsRoute,
  AuthenticatedReportsAttendanceRoute: AuthenticatedReportsAttendanceRoute,
  AuthenticatedReportsExportRoute: AuthenticatedReportsExportRoute,
  AuthenticatedStaffProfilesRoute: AuthenticatedStaffProfilesRoute,
  AuthenticatedSystemAgentRoute: AuthenticatedSystemAgentRoute,
  AuthenticatedSystemAuditLogsRoute: AuthenticatedSystemAuditLogsRoute,
  AuthenticatedSystemClinicProfileRoute: AuthenticatedSystemClinicProfileRoute,
  AuthenticatedSystemDevicesRoute: AuthenticatedSystemDevicesRoute,
  AuthenticatedSystemSettingsRoute: AuthenticatedSystemSettingsRoute,
  AuthenticatedSystemSyncRoute: AuthenticatedSystemSyncRoute,
  AuthenticatedSystemUsersRoute: AuthenticatedSystemUsersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicDeviceEventsRoute: ApiPublicDeviceEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
