/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAppointmentsRouteImport } from './routes/_authenticated/appointments'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDepartmentsRouteImport } from './routes/_authenticated/departments'
import { Route as AuthenticatedEmployeesRouteImport } from './routes/_authenticated/employees'
import { Route as AuthenticatedPatientsRouteImport } from './routes/_authenticated/patients'
import { Route as AuthenticatedPositionsRouteImport } from './routes/_authenticated/positions'
import { Route as AuthenticatedShiftsRouteImport } from './routes/_authenticated/shifts'
import { Route as AuthenticatedAppointmentsBookingRouteImport } from './routes/_authenticated/appointments.booking'
import { Route as AuthenticatedAppointmentsCalendarRouteImport } from './routes/_authenticated/appointments.calendar'
import { Route as AuthenticatedAttendanceAdjustmentsRouteImport } from './routes/_authenticated/attendance.adjustments'
import { Route as AuthenticatedAttendanceDailyRouteImport } from './routes/_authenticated/attendance.daily'
import { Route as AuthenticatedAttendanceLogsRouteImport } from './routes/_authenticated/attendance.logs'
import { Route as AuthenticatedAttendanceMonthlyRouteImport } from './routes/_authenticated/attendance.monthly'
import { Route as AuthenticatedAttendanceOvertimeRouteImport } from './routes/_authenticated/attendance.overtime'
import { Route as AuthenticatedReportsAttendanceRouteImport } from './routes/_authenticated/reports.attendance'
import { Route as AuthenticatedReportsExportRouteImport } from './routes/_authenticated/reports.export'
import { Route as AuthenticatedStaffProfilesRouteImport } from './routes/_authenticated/staff.profiles'
import { Route as AuthenticatedSystemClinicProfileRouteImport } from './routes/_authenticated/system.clinic-profile'
import { Route as AuthenticatedSystemDevicesRouteImport } from './routes/_authenticated/system.devices'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppointmentsRoute =
  AuthenticatedAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepartmentsRoute =
  AuthenticatedDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployeesRoute = AuthenticatedEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatientsRoute = AuthenticatedPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPositionsRoute = AuthenticatedPositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShiftsRoute = AuthenticatedShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppointmentsBookingRoute =
  AuthenticatedAppointmentsBookingRouteImport.update({
    id: '/booking',
    path: '/booking',
    getParentRoute: () => AuthenticatedAppointmentsRoute,
  } as any)
const AuthenticatedAppointmentsCalendarRoute =
  AuthenticatedAppointmentsCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedAppointmentsRoute,
  } as any)
const AuthenticatedAttendanceAdjustmentsRoute =
  AuthenticatedAttendanceAdjustmentsRouteImport.update({
    id: '/attendance/adjustments',
    path: '/attendance/adjustments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceDailyRoute =
  AuthenticatedAttendanceDailyRouteImport.update({
    id: '/attendance/daily',
    path: '/attendance/daily',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceLogsRoute =
  AuthenticatedAttendanceLogsRouteImport.update({
    id: '/attendance/logs',
    path: '/attendance/logs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceMonthlyRoute =
  AuthenticatedAttendanceMonthlyRouteImport.update({
    id: '/attendance/monthly',
    path: '/attendance/monthly',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceOvertimeRoute =
  AuthenticatedAttendanceOvertimeRouteImport.update({
    id: '/attendance/overtime',
    path: '/attendance/overtime',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsAttendanceRoute =
  AuthenticatedReportsAttendanceRouteImport.update({
    id: '/reports/attendance',
    path: '/reports/attendance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsExportRoute =
  AuthenticatedReportsExportRouteImport.update({
    id: '/reports/export',
    path: '/reports/export',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffProfilesRoute =
  AuthenticatedStaffProfilesRouteImport.update({
    id: '/staff/profiles',
    path: '/staff/profiles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemClinicProfileRoute =
  AuthenticatedSystemClinicProfileRouteImport.update({
    id: '/system/clinic-profile',
    path: '/system/clinic-profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemDevicesRoute =
  AuthenticatedSystemDevicesRouteImport.update({
    id: '/system/devices',
    path: '/system/devices',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/appointments': typeof AuthenticatedAppointmentsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/patients': typeof AuthenticatedPatientsRoute
  '/positions': typeof AuthenticatedPositionsRoute
  '/shifts': typeof AuthenticatedShiftsRoute
  '/appointments/booking': typeof AuthenticatedAppointmentsBookingRoute
  '/appointments/calendar': typeof AuthenticatedAppointmentsCalendarRoute
  '/attendance/adjustments': typeof AuthenticatedAttendanceAdjustmentsRoute
  '/attendance/daily': typeof AuthenticatedAttendanceDailyRoute
  '/attendance/logs': typeof AuthenticatedAttendanceLogsRoute
  '/attendance/monthly': typeof AuthenticatedAttendanceMonthlyRoute
  '/attendance/overtime': typeof AuthenticatedAttendanceOvertimeRoute
  '/reports/attendance': typeof AuthenticatedReportsAttendanceRoute
  '/reports/export': typeof AuthenticatedReportsExportRoute
  '/staff/profiles': typeof AuthenticatedStaffProfilesRoute
  '/system/clinic-profile': typeof AuthenticatedSystemClinicProfileRoute
  '/system/devices': typeof AuthenticatedSystemDevicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/appointments': typeof AuthenticatedAppointmentsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/patients': typeof AuthenticatedPatientsRoute
  '/positions': typeof AuthenticatedPositionsRoute
  '/shifts': typeof AuthenticatedShiftsRoute
  '/appointments/booking': typeof AuthenticatedAppointmentsBookingRoute
  '/appointments/calendar': typeof AuthenticatedAppointmentsCalendarRoute
  '/attendance/adjustments': typeof AuthenticatedAttendanceAdjustmentsRoute
  '/attendance/daily': typeof AuthenticatedAttendanceDailyRoute
  '/attendance/logs': typeof AuthenticatedAttendanceLogsRoute
  '/attendance/monthly': typeof AuthenticatedAttendanceMonthlyRoute
  '/attendance/overtime': typeof AuthenticatedAttendanceOvertimeRoute
  '/reports/attendance': typeof AuthenticatedReportsAttendanceRoute
  '/reports/export': typeof AuthenticatedReportsExportRoute
  '/staff/profiles': typeof AuthenticatedStaffProfilesRoute
  '/system/clinic-profile': typeof AuthenticatedSystemClinicProfileRoute
  '/system/devices': typeof AuthenticatedSystemDevicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/departments': typeof AuthenticatedDepartmentsRoute
  '/_authenticated/employees': typeof AuthenticatedEmployeesRoute
  '/_authenticated/patients': typeof AuthenticatedPatientsRoute
  '/_authenticated/positions': typeof AuthenticatedPositionsRoute
  '/_authenticated/shifts': typeof AuthenticatedShiftsRoute
  '/_authenticated/appointments/booking': typeof AuthenticatedAppointmentsBookingRoute
  '/_authenticated/appointments/calendar': typeof AuthenticatedAppointmentsCalendarRoute
  '/_authenticated/attendance/adjustments': typeof AuthenticatedAttendanceAdjustmentsRoute
  '/_authenticated/attendance/daily': typeof AuthenticatedAttendanceDailyRoute
  '/_authenticated/attendance/logs': typeof AuthenticatedAttendanceLogsRoute
  '/_authenticated/attendance/monthly': typeof AuthenticatedAttendanceMonthlyRoute
  '/_authenticated/attendance/overtime': typeof AuthenticatedAttendanceOvertimeRoute
  '/_authenticated/reports/attendance': typeof AuthenticatedReportsAttendanceRoute
  '/_authenticated/reports/export': typeof AuthenticatedReportsExportRoute
  '/_authenticated/staff/profiles': typeof AuthenticatedStaffProfilesRoute
  '/_authenticated/system/clinic-profile': typeof AuthenticatedSystemClinicProfileRoute
  '/_authenticated/system/devices': typeof AuthenticatedSystemDevicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/appointments'
    | '/dashboard'
    | '/departments'
    | '/employees'
    | '/patients'
    | '/positions'
    | '/shifts'
    | '/appointments/booking'
    | '/appointments/calendar'
    | '/attendance/adjustments'
    | '/attendance/daily'
    | '/attendance/logs'
    | '/attendance/monthly'
    | '/attendance/overtime'
    | '/reports/attendance'
    | '/reports/export'
    | '/staff/profiles'
    | '/system/clinic-profile'
    | '/system/devices'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/appointments'
    | '/dashboard'
    | '/departments'
    | '/employees'
    | '/patients'
    | '/positions'
    | '/shifts'
    | '/appointments/booking'
    | '/appointments/calendar'
    | '/attendance/adjustments'
    | '/attendance/daily'
    | '/attendance/logs'
    | '/attendance/monthly'
    | '/attendance/overtime'
    | '/reports/attendance'
    | '/reports/export'
    | '/staff/profiles'
    | '/system/clinic-profile'
    | '/system/devices'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/appointments'
    | '/_authenticated/dashboard'
    | '/_authenticated/departments'
    | '/_authenticated/employees'
    | '/_authenticated/patients'
    | '/_authenticated/positions'
    | '/_authenticated/shifts'
    | '/_authenticated/appointments/booking'
    | '/_authenticated/appointments/calendar'
    | '/_authenticated/attendance/adjustments'
    | '/_authenticated/attendance/daily'
    | '/_authenticated/attendance/logs'
    | '/_authenticated/attendance/monthly'
    | '/_authenticated/attendance/overtime'
    | '/_authenticated/reports/attendance'
    | '/_authenticated/reports/export'
    | '/_authenticated/staff/profiles'
    | '/_authenticated/system/clinic-profile'
    | '/_authenticated/system/devices'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/departments': {
      id: '/_authenticated/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AuthenticatedDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employees': {
      id: '/_authenticated/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients': {
      id: '/_authenticated/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AuthenticatedPatientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/positions': {
      id: '/_authenticated/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof AuthenticatedPositionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shifts': {
      id: '/_authenticated/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof AuthenticatedShiftsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appointments/booking': {
      id: '/_authenticated/appointments/booking'
      path: '/booking'
      fullPath: '/appointments/booking'
      preLoaderRoute: typeof AuthenticatedAppointmentsBookingRouteImport
      parentRoute: typeof AuthenticatedAppointmentsRoute
    }
    '/_authenticated/appointments/calendar': {
      id: '/_authenticated/appointments/calendar'
      path: '/calendar'
      fullPath: '/appointments/calendar'
      preLoaderRoute: typeof AuthenticatedAppointmentsCalendarRouteImport
      parentRoute: typeof AuthenticatedAppointmentsRoute
    }
    '/_authenticated/attendance/adjustments': {
      id: '/_authenticated/attendance/adjustments'
      path: '/attendance/adjustments'
      fullPath: '/attendance/adjustments'
      preLoaderRoute: typeof AuthenticatedAttendanceAdjustmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/daily': {
      id: '/_authenticated/attendance/daily'
      path: '/attendance/daily'
      fullPath: '/attendance/daily'
      preLoaderRoute: typeof AuthenticatedAttendanceDailyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/logs': {
      id: '/_authenticated/attendance/logs'
      path: '/attendance/logs'
      fullPath: '/attendance/logs'
      preLoaderRoute: typeof AuthenticatedAttendanceLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/monthly': {
      id: '/_authenticated/attendance/monthly'
      path: '/attendance/monthly'
      fullPath: '/attendance/monthly'
      preLoaderRoute: typeof AuthenticatedAttendanceMonthlyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/overtime': {
      id: '/_authenticated/attendance/overtime'
      path: '/attendance/overtime'
      fullPath: '/attendance/overtime'
      preLoaderRoute: typeof AuthenticatedAttendanceOvertimeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/attendance': {
      id: '/_authenticated/reports/attendance'
      path: '/reports/attendance'
      fullPath: '/reports/attendance'
      preLoaderRoute: typeof AuthenticatedReportsAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/export': {
      id: '/_authenticated/reports/export'
      path: '/reports/export'
      fullPath: '/reports/export'
      preLoaderRoute: typeof AuthenticatedReportsExportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/profiles': {
      id: '/_authenticated/staff/profiles'
      path: '/staff/profiles'
      fullPath: '/staff/profiles'
      preLoaderRoute: typeof AuthenticatedStaffProfilesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/clinic-profile': {
      id: '/_authenticated/system/clinic-profile'
      path: '/system/clinic-profile'
      fullPath: '/system/clinic-profile'
      preLoaderRoute: typeof AuthenticatedSystemClinicProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/devices': {
      id: '/_authenticated/system/devices'
      path: '/system/devices'
      fullPath: '/system/devices'
      preLoaderRoute: typeof AuthenticatedSystemDevicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAppointmentsRouteChildren {
  AuthenticatedAppointmentsBookingRoute: typeof AuthenticatedAppointmentsBookingRoute
  AuthenticatedAppointmentsCalendarRoute: typeof AuthenticatedAppointmentsCalendarRoute
}

const AuthenticatedAppointmentsRouteChildren: AuthenticatedAppointmentsRouteChildren =
  {
    AuthenticatedAppointmentsBookingRoute:
      AuthenticatedAppointmentsBookingRoute,
    AuthenticatedAppointmentsCalendarRoute:
      AuthenticatedAppointmentsCalendarRoute,
  }

const AuthenticatedAppointmentsRouteWithChildren =
  AuthenticatedAppointmentsRoute._addFileChildren(
    AuthenticatedAppointmentsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppointmentsRoute: typeof AuthenticatedAppointmentsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepartmentsRoute: typeof AuthenticatedDepartmentsRoute
  AuthenticatedEmployeesRoute: typeof AuthenticatedEmployeesRoute
  AuthenticatedPatientsRoute: typeof AuthenticatedPatientsRoute
  AuthenticatedPositionsRoute: typeof AuthenticatedPositionsRoute
  AuthenticatedShiftsRoute: typeof AuthenticatedShiftsRoute
  AuthenticatedAttendanceAdjustmentsRoute: typeof AuthenticatedAttendanceAdjustmentsRoute
  AuthenticatedAttendanceDailyRoute: typeof AuthenticatedAttendanceDailyRoute
  AuthenticatedAttendanceLogsRoute: typeof AuthenticatedAttendanceLogsRoute
  AuthenticatedAttendanceMonthlyRoute: typeof AuthenticatedAttendanceMonthlyRoute
  AuthenticatedAttendanceOvertimeRoute: typeof AuthenticatedAttendanceOvertimeRoute
  AuthenticatedReportsAttendanceRoute: typeof AuthenticatedReportsAttendanceRoute
  AuthenticatedReportsExportRoute: typeof AuthenticatedReportsExportRoute
  AuthenticatedStaffProfilesRoute: typeof AuthenticatedStaffProfilesRoute
  AuthenticatedSystemClinicProfileRoute: typeof AuthenticatedSystemClinicProfileRoute
  AuthenticatedSystemDevicesRoute: typeof AuthenticatedSystemDevicesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppointmentsRoute: AuthenticatedAppointmentsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepartmentsRoute: AuthenticatedDepartmentsRoute,
  AuthenticatedEmployeesRoute: AuthenticatedEmployeesRoute,
  AuthenticatedPatientsRoute: AuthenticatedPatientsRoute,
  AuthenticatedPositionsRoute: AuthenticatedPositionsRoute,
  AuthenticatedShiftsRoute: AuthenticatedShiftsRoute,
  AuthenticatedAttendanceAdjustmentsRoute:
    AuthenticatedAttendanceAdjustmentsRoute,
  AuthenticatedAttendanceDailyRoute: AuthenticatedAttendanceDailyRoute,
  AuthenticatedAttendanceLogsRoute: AuthenticatedAttendanceLogsRoute,
  AuthenticatedAttendanceMonthlyRoute: AuthenticatedAttendanceMonthlyRoute,
  AuthenticatedAttendanceOvertimeRoute: AuthenticatedAttendanceOvertimeRoute,
  AuthenticatedReportsAttendanceRoute: AuthenticatedReportsAttendanceRoute,
  AuthenticatedReportsExportRoute: AuthenticatedReportsExportRoute,
  AuthenticatedStaffProfilesRoute: AuthenticatedStaffProfilesRoute,
  AuthenticatedSystemClinicProfileRoute: AuthenticatedSystemClinicProfileRoute,
  AuthenticatedSystemDevicesRoute: AuthenticatedSystemDevicesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
